---
cro: 1
endpoints: 
  - 
    "host-env": "BEGUMPURA_HOST"
    "id": "http"
    "name": "HTTP"
    "port-env": "BEGUMPURA_PORT"
    "protocol": "http"
entrypoint: service.raku
env: []
id: begumpura
links: []
name: "begumpura"
ignore:
  - "node_modules/"
...